### ISSUE TITLE
Remove **all** old backups

### ISSUE THREAD

**Issue by astyagun** [vishr/local-history#31]
Currently plugin can delete old backups, but only for the file being edited. If you for example have old backups left from some old project and you won't edit files from that project anymore (because you just don't have those files anymore), then those backups will stay there forever.

Useful option would be to automatically remove **all** old backups, and not only backups of the file that user edits.

**Comment by jrappen** [comment]
`Tools > Local History > Delete Local History > Permanently delete all`

or

`Preferences > Package Settings > Local History > Delete Local History > Permanently delete all`

---

Please close issue

**Comment by astyagun** [comment]
👍
