### ISSUE TITLE
ST3 doesn't save any history when set "history_on_close" to true

### ISSUE THREAD

**Issue by imyzf** [vishr/local-history#59]
If I set "history_on_close": true, it never saves any history including closing the file.

I'm using build 3083 on Fedora 21.

**Comment by vishr** [comment]
@imyzf I have moved on from ST, and it's really hard for me to debug on various platform. You might want to check pull requests and issues. I am open to accept PR.

**Comment by imyzf** [comment]
@vishr Sorry, I'm a javascript programmer and have never written in python. So I don't know how to fix this bug. But your package is still very excellent without history_on_close. It helps me a lot.
