### ISSUE TITLE
not working on the latest version published in 2016.06.23

### ISSUE THREAD

**Issue by Awakening-j** [vishr/local-history#70]
no file saved to history, and the contextmenu of `history` not active.  
![image](https://cloud.githubusercontent.com/assets/8085088/16329921/54298590-3a18-11e6-878f-6c2f50c73d24.png)

and the command `history` not working at all

**Comment by jrappen** [comment]
Maybe do a rollback until I've found a solution. Local History works for me except the `SaveNow` text command (see #69).

**Comment by Awakening-j** [comment]
waiting for update

**Comment by Awakening-j** [comment]
my env:

OS X EI Captian
ST 2 build 2221

**Comment by Awakening-j** [comment]
@jrappen where is `SaveNow`?

**Comment by jrappen** [comment]
[master@0fef83b/LocalHistory.py#L145-L149](https://github.com/vishr/local-history/blob/0fef83b3d8e715bf45520fc920ba09ee678ee6e9/LocalHistory.py#L145-L149)
