### ISSUE TITLE
Local History settings

### ISSUE THREAD

**Issue by Kristinita** [vishr/local-history#76]
1. ` file_size_limit` — what is the maximum value?
2. `history_on_focus_lost` and `history_on_load` — could you comment what these settings?
3. `history_on_close` — unfortunately, I do not understand comment (perhaps because do not speak in English). Is it true, I realized that at a value of `true`, if I close the file but does not save the file, a file with unsaved changes will remain in the Local History folder?

Thanks.

**Comment by jrappen** [comment]
* 1) I haven't tested it, probably is the max value of that JSON type of integer (my guess).
* 2a) If the window looses focus (for example by switching to another program), Local History will check if a history file exists. And if so, check if it is up-to-date.
* 2b) Same as above only in the event of opening the file.
* 3) If set to `false`, Local History will keep a revision every time you save a file while editing it in Sublime Text. If set to `true`, Local History will only save a revision of the state the file was in, when you closed the tab with the file you are editing.

**Comment by jrappen** [comment]
@Kristinita were you running into problems with 1?

**Comment by Kristinita** [comment]
@jrappen, thanks for answers!

* 1) No, I didn't face problems so far. I established `"file_size_limit": 99999999`, and I don't know, whether it is bad.
* 2а) I wrote in my `Settings - User` file `"history_on_focus_lost": true` but I don't see that there were some changes. When `"history_on_load": true`, I see that something occurs in Status Bar but when `"history_on_focus_lost": true,` , anything in Status Bar doesn't change.

Thanks.

**Comment by bahrisaiful** [comment]
How to change Local History Default Path In Sublime Text 3
I've tried to change but could not

'{
"history_path": "D:/historysublime"
}'

**Comment by rhamzeh** [comment]
@bahrisaiful You also need to set portable: false. By default it is true, and when set to true, it always defaults to the same directory: ".sublime/Local History"

See: [Line 43 in LocalHistory.py](https://github.com/vishr/local-history/blob/3256c6976effca9aa68c87cb431fb908722b5757/LocalHistory.py#L43)

**Comment by bahrisaiful** [comment]
@rhamzeh thanks for answer

`{
    "history_retention": 0, // number of days to keep files, 0 to disable deletion
    "format_timestamp": "%Y%m%d%H%M%S", // file_name-XXXXXXXX.file_extension
    "history_on_close": true, // only save LocalHistory after closing a file, not when original was saved 
    "history_on_focus_lost": false,
    "history_on_load": true,
 "history_path": "D:/historysublime", // redirect '~/.sublime/Local History/...' to some other place if "portable": false
    "portable": false, // save to 'Sublime Text/Data/.sublime/Local History/...' instead of '~/.sublime/Local History/...'
    "file_size_limit": 4194304 // 4 MB
}
`

**Comment by jrappen** [comment]
@bahrisaiful You'll need `"portable": false` as explained above. Did you try `D:\historysublime` instead?

@Kristinita If you look at [LocalHistory.py#L100](https://github.com/vishr/local-history/blob/master/LocalHistory.py#L100) it will only save changes if the view is dirty as well.

**Comment by Kristinita** [comment]
@jrappen , I apologize, what is «view is dirty»? Thanks.

**Comment by jrappen** [comment]
@Kristinita compare `sublime.view.is_dirty()` on https://www.sublimetext.com/docs/3/api_reference.html

**Comment by Kristinita** [comment]
@jrappen, OK I understood. When `"history_on_focus_lost": true` If I remove the focus from Sublime Text 3, when I open the file in which changes are not saved in the Status Bar appears` Local History: File not saved, no changed for "MyFile.example"`.

But what is the use? Why `"history_on_focus_lost": true` is necessary? Local History doesn't keep additional copies of the file.

Thanks.

**Comment by jrappen** [comment]
* As you wrote above, Local History didn't save (another copy of that snapshot), because a copy of that snapshot already exists. The contents of the archived files would be the same.
* When `"history_on_focus_lost": true` Local History will save a snapshot to the archive if Sublime Text looses focus (you switch to the desktop or another app), if (1) no archived files exist or (2) there have been changes.
