### ISSUE TITLE
[Feature request] Named backups

### ISSUE THREAD

**Issue by Kristinita** [vishr/local-history#92]
### 1. Request

It would be nice, if would be possible to create named backups.

### 1. Justification

For example, I write working code in a file. I wrote working code and I save my file. Then I continue to write the code in a file → my code doesn't work. I want to see version of my file with working code, that

1. I can to diff between current and working versions of my file,
1. I can revert my file to working versions.

I work in file → <kbd>Ctrl+Shift+P</kbd> → `Local History: Open` → I can see saved copies:

![Copies](http://i.imgur.com/J4py6Rt.png)

But I don't understand, which of these backups is the right working file. It would be nice, if would be possible to make human names.

### 3. Desirable behavior

☐ I write working code → <kbd>Ctrl+Shift+P</kbd> → `Local History: Create Named Backup` → quick panel shown for me → I wrote in quick panel custom name of my backup → <kbd>Enter</kbd> → named copy successful saved for me.
☐ I want to see named copy. I open the file I backup → `Local History: Open` → I see quick panel with all backups of my file → I select named backup → named backup file open for me.

Thanks.

**Comment by Pictor13** [comment]
Did you try to use the the command ```Local History: Create Snapshot``` ?

**Comment by Kristinita** [comment]
@Pictor13 , thank you! What I need!
